package Front;

import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import javax.swing.table.TableRowSorter;

/**
 * *
 *
 * @author Franklyn Escobar
 */
public class form_nuevo_prestamo extends javax.swing.JFrame {

    /**
     * Creates new form form_new_prestamo
     */
    DefaultTableModel dm;
    private JComboBox combo;

    public form_nuevo_prestamo() {
        initComponents();
        cerrar();
        txt_id.setVisible(false);
        setResizable(false);
        SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
        txt_fecha_creacion.setEditable(false);
        LocalDate local = LocalDate.now();
        Date date = java.sql.Date.valueOf(local);
        String fecha = dformat.format(date);
        txt_fecha_creacion.setText(fecha);
        txt_monto_a.setEditable(false);
        txt_ganan.setEditable(false);
        txt_id.setEditable(false);
        txt_couta.setEditable(false);
        txt_cuota_pagar.setEditable(false);
        conexcion con = new conexcion();
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Nombres");
        tbl.addColumn("Apellidos");
        tbl.addColumn("DPI");
        tbl.addColumn("Teléfono");
        tbla_clie.setModel(tbl);
        String query = "SELECT id_cliente,nombre_cliente,apellido_cliente,dpi,telefono FROM tbl_cliente";
        String query_socio = "SELECT nombres_socio from tbl_socio";
        String[] dato = new String[5];
        Statement str, str_socio;
        combo = new JComboBox();

        try {

            str = con.getConnection().createStatement();
            ResultSet result = str.executeQuery(query);

            str_socio = con.getConnection().createStatement();
            ResultSet result_socio = str_socio.executeQuery(query_socio);

            while (result_socio.next()) {
                cmb_socio.addItem(result_socio.getString(1));
            }

            while (result.next()) {
                dato[0] = result.getString(1);
                dato[1] = result.getString(2);
                dato[2] = result.getString(3);
                dato[3] = result.getString(4);
                dato[4] = result.getString(5);

                tbl.addRow(dato);
            }
            str.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error!, la llamada no pudo ser agregada a la base de datos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dpi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_monto_s = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_interes = new javax.swing.JTextField();
        cmb_plazo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txt_ganan = new javax.swing.JTextField();
        txt_monto_a = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        chk_gara = new javax.swing.JCheckBox();
        txt_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbla_clie = new javax.swing.JTable();
        date_cre = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txt_couta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cuota_pagar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmb_socio = new javax.swing.JComboBox<String>();
        txt_fecha_creacion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitud de Nuevo Préstamo");
        setMinimumSize(new java.awt.Dimension(980, 580));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(71, 155, 56, 26);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("DPI");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(71, 116, 37, 26);

        txt_nombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(139, 153, 212, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Solicitud de  Nuevo Préstamo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 0, 300, 39);

        txt_dpi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_dpi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_dpiKeyReleased(evt);
            }
        });
        getContentPane().add(txt_dpi);
        txt_dpi.setBounds(139, 116, 212, 28);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 480, 108, 46);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 480, 110, 44);

        txt_monto_s.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_monto_s.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_monto_sKeyTyped(evt);
            }
        });
        getContentPane().add(txt_monto_s);
        txt_monto_s.setBounds(178, 340, 127, 28);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Monto Solicitado");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(71, 342, 101, 26);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Interés");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(313, 342, 45, 26);

        txt_interes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_interes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_interesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_interesKeyTyped(evt);
            }
        });
        getContentPane().add(txt_interes);
        txt_interes.setBounds(364, 340, 49, 28);

        cmb_plazo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plazo", "Diario", "Semanal", "Mensual" }));
        cmb_plazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_plazoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_plazo);
        cmb_plazo.setBounds(255, 392, 80, 26);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Forma de pago");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(164, 393, 85, 26);
        getContentPane().add(txt_ganan);
        txt_ganan.setBounds(788, 440, 95, 28);
        getContentPane().add(txt_monto_a);
        txt_monto_a.setBounds(788, 391, 95, 28);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Ganancia");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(714, 442, 56, 26);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Monto a Pagar");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(685, 393, 85, 26);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Fecha Creación");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(431, 342, 91, 26);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Fecha Finalización");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(628, 342, 100, 26);

        chk_gara.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chk_gara.setText("Garantía");
        chk_gara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_garaActionPerformed(evt);
            }
        });
        getContentPane().add(chk_gara);
        chk_gara.setBounds(71, 390, 75, 32);
        getContentPane().add(txt_id);
        txt_id.setBounds(930, 0, 46, 26);

        tbla_clie.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbla_clie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbla_clie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbla_clieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbla_clie);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(71, 199, 812, 123);
        getContentPane().add(date_cre);
        date_cre.setBounds(740, 340, 143, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Cuotas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(551, 399, 37, 14);

        txt_couta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_couta);
        txt_couta.setBounds(600, 393, 79, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Cuota a pagar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(353, 399, 73, 14);

        txt_cuota_pagar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_cuota_pagar);
        txt_cuota_pagar.setBounds(438, 393, 95, 22);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Socio");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(568, 442, 38, 26);

        cmb_socio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmb_socio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Socio" }));
        getContentPane().add(cmb_socio);
        cmb_socio.setBounds(624, 441, 72, 24);

        txt_fecha_creacion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_fecha_creacion);
        txt_fecha_creacion.setBounds(534, 344, 82, 22);

        jPanel1.setBackground(new java.awt.Color(187, 187, 187,80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 100, 730, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prestamo_picture.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(900, 666));
        jLabel4.setMinimumSize(new java.awt.Dimension(900, 666));
        jLabel4.setPreferredSize(new java.awt.Dimension(900, 666));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1070, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_plazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_plazoActionPerformed
        int seleccion;
        double monto , total;
        seleccion = cmb_plazo.getSelectedIndex();
        
        if (txt_monto_s.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese monto");
        } else {
            if (txt_monto_s.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese interes");
            } else {
                switch (seleccion) {
                    case 1:
                        txt_couta.setText("23");
                        monto = Double.parseDouble(txt_monto_a.getText());
                        total = monto / 23;
                        txt_cuota_pagar.setText(Double.toString(total));
                        break;
                    case 2:
                        txt_couta.setText("4");
                        monto = Double.parseDouble(txt_monto_a.getText());
                        total = monto / 4;
                        txt_cuota_pagar.setText(Double.toString(total));
                        break;
                    case 3:
                        txt_couta.setText("1");
                        monto = Double.parseDouble(txt_monto_a.getText());
                        total = monto / 1;
                        txt_cuota_pagar.setText(Double.toString(total));
                        break;
                        
                }
            }
        }
    }//GEN-LAST:event_cmb_plazoActionPerformed

    private void chk_garaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_garaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_garaActionPerformed

    private void tbla_clieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbla_clieMouseClicked
        int seleccion = tbla_clie.rowAtPoint(evt.getPoint());
        txt_id.setText(String.valueOf(tbla_clie.getValueAt(seleccion, 0)));
        txt_dpi.setText(String.valueOf(tbla_clie.getValueAt(seleccion, 3)));
        txt_nombre.setText(String.valueOf(tbla_clie.getValueAt(seleccion, 1)));
    }//GEN-LAST:event_tbla_clieMouseClicked
    private void filtro(String consulta, JTable jtableBuscar) {
        dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        int seleccion = cmb_plazo.getSelectedIndex(), cuota;
        LocalDate local = LocalDate.now();
        int socio = cmb_socio.getSelectedIndex();
        String fec_c;
        String fec_f;
        int estadod = 0, res = 0, ga = 0;
        int id_cliente;
        int garantia = 0;
        double monto;
        double interes;
        double monto_a_pa;
        double ganancia, cuota_tot;
        conexcion con = new conexcion();
        String query = "INSERT INTO tbl_prestamo (id_prestamo,monto,interes,fecha_creacion,fecha_finalizacion,monto_interes,ganancia,estado_garantia,"
                + "cuotas,total_cuota"
                + ",id_cliente,id_plazo,estado,saldo_faltante,cuota_faltante,id_socio) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?,?,?,?)";
        String query2 = "SELECT id_cliente,estado FROM tbl_prestamo";
        String[] dato = new String[2];
        Statement str1;

        try {

            str1 = con.getConnection().createStatement();
            ResultSet result = str1.executeQuery(query2);
            while (result.next()) {

                dato[0] = result.getString(1);
                dato[1] = result.getString(2);
                if (txt_id.getText().equals(dato[0]) && dato[1].equals("1")) {
                    estadod = 1;
                } else {
                }
            }
        } catch (SQLException e) {

        }

        if (estadod == 1) {
            JOptionPane.showMessageDialog(null, "El cliente tiene un prestamo activo");
        } else {
            if (chk_gara.isSelected() == true) {
                garantia = 1;
            }
            if (txt_id.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Seleccione un cliente");
            } else {
                if (txt_monto_s.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Ingrese Monto Solicitado");
                } else {
                    if (txt_interes.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Ingrese el Interes");
                    } else {
                        if (date_cre.getDate() == null) {
                            JOptionPane.showMessageDialog(null, "Ingrese  fecha inicio");
                        } else {
                                if (seleccion == 0) {
                                    JOptionPane.showMessageDialog(null, "Seleccione un Plazo");
                                } else {
                                    if (socio == 0) {
                                        JOptionPane.showMessageDialog(null, "Seleccione un Socio");
                                    } else {

                                        monto = Double.parseDouble(txt_monto_s.getText());
                                        interes = Double.parseDouble(txt_interes.getText());
                                        id_cliente = Integer.parseInt(txt_id.getText());
                                        ganancia = Double.parseDouble(txt_ganan.getText());
                                        monto_a_pa = Double.parseDouble(txt_monto_a.getText());
                                        fec_f = dformat.format(date_cre.getDate());
                                        fec_c = local.toString();
                                        cuota = Integer.parseInt(txt_couta.getText());
                                        cuota_tot = Double.parseDouble(txt_cuota_pagar.getText());

                                        try {
                                            PreparedStatement str = con.getConnection().prepareStatement(query);
                                            str.setNull(1, java.sql.Types.BIGINT);
                                            str.setDouble(2, monto);
                                            str.setDouble(3, interes);
                                            str.setString(4, fec_c);
                                            str.setString(5, fec_f);
                                            str.setDouble(6, monto_a_pa);
                                            str.setDouble(7, ganancia);
                                            str.setInt(8, garantia);
                                            str.setInt(9, cuota);
                                            str.setDouble(10, cuota_tot);
                                            str.setInt(11, id_cliente);
                                            str.setInt(12, seleccion);
                                            str.setInt(13, 1);
                                            str.setDouble(14, monto_a_pa);
                                            str.setInt(15, cuota);
                                            str.setInt(16, socio);

                                            res = str.executeUpdate();
                                            
        
                                            if (res > 0) {
                                                JOptionPane.showMessageDialog(null, "Ingreso completado");
                                                ga = 1;
                                            txt_nombre.setText(null);
                                            txt_dpi.setText(null);
                                            txt_couta.setText(null);
                                            txt_cuota_pagar.setText(null);
                                            txt_ganan.setText(null);
                                            txt_id.setText(null);
                                            txt_interes.setText(null);
                                            txt_monto_a.setText(null);
                                            txt_monto_s.setText(null);
                                            cmb_plazo.setSelectedIndex(0);
                                            cmb_socio.setSelectedIndex(0);
                                            chk_gara.setAction(null);
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Error");
                                            }
                                            str.close();
                                        } catch (SQLException e) {
                                            JOptionPane.showMessageDialog(null, "Error!, la llamada no pudo ser agregada a la base de datos." + e);
                                        }
                                        con.desconectar();
                                    }
                                          
                                }
                            }
                        }
                    
                }
            }
                                            
        }
        if (ga == 1) {
            if (garantia == 1) {
                this.setVisible(false);
                new form_garantia().setVisible(true);
            }
        }
        //con.desconectar();
                                           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        filtro(txt_nombre.getText(), tbla_clie);
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void txt_dpiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dpiKeyReleased
        filtro(txt_dpi.getText().toUpperCase(), tbla_clie);
    }//GEN-LAST:event_txt_dpiKeyReleased

    private void txt_interesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_interesKeyReleased
        double monto;
        double interes;
        double total;
        double ganancia;
        String gana, tot;
        DecimalFormat dc =new DecimalFormat("0.00");
        try{
        if (txt_monto_s.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Ingrese Monto Solicitado Primero");
        } else {
            if (txt_interes.getText().isEmpty()) {
                //JOptionPane.showMessageDialog(null, "Ingrese Monto Solicitado Primero");
            } else {
                monto = Double.parseDouble(txt_monto_s.getText());
                interes = Double.parseDouble(txt_interes.getText());
                interes = interes / 100;
                total = monto * interes;
                ganancia = total + monto;
                tot = String.valueOf(ganancia);
                gana = String.valueOf(total);
                txt_monto_a.setText(dc.format(total));
                txt_ganan.setText(dc.format(ganancia));
            }
        }
        }catch(NumberFormatException ex){
            
        }
    }//GEN-LAST:event_txt_interesKeyReleased

    private void txt_monto_sKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_monto_sKeyTyped
        char valida = evt.getKeyChar();
        if (Character.isLetter(valida)||Character.isWhitespace(valida)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txt_monto_sKeyTyped

    private void txt_interesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_interesKeyTyped
        char valida = evt.getKeyChar();
        if (Character.isLetter(valida)||Character.isWhitespace(valida)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txt_interesKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desea regresar?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
        form_principal frm = new form_principal();
        frm.setVisible(true);
        this.dispose();
        }
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void cerrar() {
        try {
            this.setDefaultCloseOperation(form_newcobrador.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            }
            );
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desa Salir?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_nuevo_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_nuevo_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_nuevo_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_nuevo_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_nuevo_prestamo().setVisible(true);
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_gara;
    private javax.swing.JComboBox cmb_plazo;
    private javax.swing.JComboBox<String> cmb_socio;
    private com.toedter.calendar.JDateChooser date_cre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbla_clie;
    private javax.swing.JTextField txt_couta;
    private javax.swing.JTextField txt_cuota_pagar;
    private javax.swing.JTextField txt_dpi;
    private javax.swing.JTextField txt_fecha_creacion;
    private javax.swing.JTextField txt_ganan;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_interes;
    private javax.swing.JTextField txt_monto_a;
    private javax.swing.JTextField txt_monto_s;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
