/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franklyn Escobar
 */
public class form_comisiones extends javax.swing.JFrame {

    /**
     * Creates new form form_comisiones
     */
    conexcion con = new conexcion();

    public form_comisiones() {
        initComponents();
        cerrar();
        setResizable(false);
        this.setLocationRelativeTo(null);
        txt_id_co.setVisible(false);
        txt_id_pres.setVisible(false);
        DefaultTableModel tbl = new DefaultTableModel();

        SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");

        LocalDate local = LocalDate.now();
        Date date = java.sql.Date.valueOf(local);
        String fecha = dformat.format(date);
        txt_pagocomision.setText(fecha);
        tbl.addColumn("ID");
        tbl.addColumn("Nombre del cliente");
        tbl.addColumn("Monto total del prestamo");
        tbl.addColumn("Ganancia");
        tbl.addColumn("Fecha creacion");
        tbl.addColumn("Fecha Finalizacion");
        tbl_datosprest.setModel(tbl);

        DefaultTableModel tbl_co = new DefaultTableModel();
        tbl_co.addColumn("ID");
        tbl_co.addColumn("Nombre del cobrador");
        tbl_co.addColumn("Apellido del cobrador");
        tbl_co.addColumn("DPI");
        tbl_datoscobra.setModel(tbl_co);
        String query_pres = "select id_prestamo,nombre_cliente,monto_interes,ganancia, fecha_creacion, fecha_finalizacion from tbl_prestamo\n"
                + "inner join tbl_cliente\n"
                + "on tbl_prestamo.id_cliente=tbl_cliente.id_cliente where estado=0";
        String query_co = " select id_cobrador,nombre,apellido,dpi from tbl_cobrador";
        String[] dato_pres = new String[7];
        String[] dato_co = new String[4];
        Statement str_co;
        Statement str_pre;

        try {

            str_pre = con.getConnection().createStatement();
            ResultSet result = str_pre.executeQuery(query_pres);
            str_co = con.getConnection().createStatement();
            ResultSet result_co = str_co.executeQuery(query_co);

            while (result.next()) {
                dato_pres[0] = result.getString(1);
                dato_pres[1] = result.getString(2);
                dato_pres[2] = result.getString(3);
                dato_pres[3] = result.getString(4);
                dato_pres[4] = result.getString(5);
                dato_pres[5] = result.getString(6);

                tbl.addRow(dato_pres);
            }
            while (result_co.next()) {
                dato_co[0] = result_co.getString(1);
                dato_co[1] = result_co.getString(2);
                dato_co[2] = result_co.getString(3);
                dato_co[3] = result_co.getString(4);

                tbl_co.addRow(dato_co);
            }
            str_co.close();
            str_pre.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error!, la llamada no pudo ser agregada a la base de datos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datoscobra = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_prestnombre = new javax.swing.JTextField();
        txt_presmonto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_datosprest = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_comision = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();
        txt_pagocomision = new javax.swing.JTextField();
        txt_id_co = new javax.swing.JTextField();
        txt_id_pres = new javax.swing.JTextField();
        txt_desc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso Comisiones");
        setMinimumSize(new java.awt.Dimension(645, 647));
        setPreferredSize(new java.awt.Dimension(645, 647));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("INGRESO COMISIÓN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(259, 6, 172, 41);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 92, 54, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(44, 144, 47, 14);

        txt_nombres.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_nombres);
        txt_nombres.setBounds(114, 96, 326, 22);

        txt_apellidos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_apellidos);
        txt_apellidos.setBounds(114, 140, 326, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Datos Cobrador");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(292, 59, 99, 27);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Datos Prestamo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(288, 263, 106, 24);

        tbl_datoscobra.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tbl_datoscobra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datoscobra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datoscobraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_datoscobra);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(114, 172, 500, 73);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Nombres");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(44, 299, 44, 25);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Monto ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(44, 346, 37, 14);

        txt_prestnombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_prestnombre);
        txt_prestnombre.setBounds(106, 300, 323, 30);

        txt_presmonto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_presmonto);
        txt_presmonto.setBounds(106, 342, 323, 30);

        tbl_datosprest.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tbl_datosprest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datosprest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datosprestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_datosprest);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(106, 376, 500, 74);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Ganancia");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(44, 474, 44, 22);

        txt_monto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_monto);
        txt_monto.setBounds(106, 474, 62, 22);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Comisión Q");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(180, 478, 58, 14);

        txt_comision.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_comision);
        txt_comision.setBounds(244, 474, 62, 22);

        btn_guardar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar);
        btn_guardar.setBounds(234, 570, 85, 45);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Fecha Pago comisión");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(335, 478, 100, 14);

        btn_regresar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar);
        btn_regresar.setBounds(331, 568, 77, 49);

        txt_pagocomision.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_pagocomision);
        txt_pagocomision.setBounds(453, 474, 87, 22);
        getContentPane().add(txt_id_co);
        txt_id_co.setBounds(623, 65, 14, 14);
        getContentPane().add(txt_id_pres);
        txt_id_pres.setBounds(623, 269, 14, 12);

        txt_desc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_desc);
        txt_desc.setBounds(276, 514, 264, 36);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Descripcion");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 525, 58, 14);

        jPanel1.setBackground(new java.awt.Color(187, 187, 187,80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 50, 590, 200);

        jPanel2.setBackground(new java.awt.Color(187, 187, 187,80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 260, 590, 300);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Commision background.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 643, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    validaciones validarDatos = new validaciones();


    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        String Descr;
        double monto;
        LocalDate local = LocalDate.now();
        String fecha = local.toString();
        int dato_final = 0;

        if (txt_nombres.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un Cobrador:");
        } else {
            if (txt_apellidos.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Seleccione un Cobrador:");
            } else {
                if (txt_prestnombre.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Seleccione un Prestamo:");
                } else {
                    if (txt_presmonto.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Seleccione un Prestamo");
                    } else {
                        if (txt_id_co.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Seleccione un cobrador");
                        } else {
                            if (txt_comision.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Ingrese el dinero de la Comision");
                            } else {
                                Descr = txt_desc.getText();
                                monto = Double.parseDouble(txt_comision.getText());
                                int id = Integer.parseInt(txt_id_pres.getText());
                                int id_cobrador= Integer.parseInt(txt_id_co.getText());

                                String query = "INSERT INTO tbl_comision (id_comision,descripcion,monto_comision,fecha_pago,id_prestamo) VALUES ( ?, ?, ?, ?, ?)";
                                String query_pagos = "INSERT INTO tbl_detalle_comision (id_cobrador,id_comision) VALUES ( ?, ?)";
                                String query_last = "select max(id_comision) from tbl_comision";
                                try {
                                    PreparedStatement str = con.getConnection().prepareStatement(query);
                                    str.setNull(1, java.sql.Types.BIGINT);
                                    str.setString(2, Descr);
                                    str.setDouble(3, monto);
                                    str.setString(4, fecha);
                                    str.setInt(5, id);

                                    int res = str.executeUpdate();
                                    if (res > 0) {
                                        try {
                                            PreparedStatement str_last = con.getConnection().prepareStatement(query_last);

                                            ResultSet result = str_last.executeQuery(query_last);
                                            while (result.next()) {
                                                
                                                dato_final = result.getInt(1);
                                            }
                                            PreparedStatement str_pago = con.getConnection().prepareStatement(query_pagos);
                                            str_pago.setInt(1, id_cobrador);
                                            str_pago.setInt(2, dato_final);
                                            int res_pago = str_pago.executeUpdate();
                                            if (res > 0) {
                                                JOptionPane.showMessageDialog(null, "Ingreso Correcto");
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Error");
                                            }
                                            str_pago.close();
                                            str_last.close();
                                        } catch (SQLException e) {
                                            JOptionPane.showMessageDialog(null, "Error!, la llamada no pudo ser agregada a la base de datos." + e);
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Error");
                                    }
                                    str.close();
                                } catch (SQLException e) {
                                    JOptionPane.showMessageDialog(null, "Error!, la llamada no pudo ser agregada a la base de datos." + e);
                                }
                            }
                        }
                    }
                }
            }

        }


    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tbl_datoscobraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datoscobraMouseClicked
        int seleccion = tbl_datoscobra.rowAtPoint(evt.getPoint());
        txt_id_co.setText(String.valueOf(tbl_datoscobra.getValueAt(seleccion, 0)));
        txt_nombres.setText(String.valueOf(tbl_datoscobra.getValueAt(seleccion, 1)));
        txt_apellidos.setText(String.valueOf(tbl_datoscobra.getValueAt(seleccion, 2)));
    }//GEN-LAST:event_tbl_datoscobraMouseClicked

    private void tbl_datosprestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datosprestMouseClicked
        int seleccion = tbl_datosprest.rowAtPoint(evt.getPoint());
        txt_id_pres.setText(String.valueOf(tbl_datosprest.getValueAt(seleccion, 0)));
        txt_prestnombre.setText(String.valueOf(tbl_datosprest.getValueAt(seleccion, 1)));
        txt_presmonto.setText(String.valueOf(tbl_datosprest.getValueAt(seleccion, 2)));
        txt_monto.setText(String.valueOf(tbl_datosprest.getValueAt(seleccion, 3)));
    }//GEN-LAST:event_tbl_datosprestMouseClicked

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desea regresar?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
        form_principal frm = new form_principal();
        frm.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btn_regresarActionPerformed
  public void cerrar() {
        try {
            this.setDefaultCloseOperation(form_newcobrador.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            }
            );
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desa Salir?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_comisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_comisiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_datoscobra;
    private javax.swing.JTable tbl_datosprest;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_comision;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_id_co;
    private javax.swing.JTextField txt_id_pres;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_pagocomision;
    private javax.swing.JTextField txt_presmonto;
    private javax.swing.JTextField txt_prestnombre;
    // End of variables declaration//GEN-END:variables
}
