/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class form_Recuperar_Contraseña extends javax.swing.JFrame {
    public conexcion cnx = new conexcion();
    
    /**
     * Creates new form form_Recuperar_Contraseña
     */
    public form_Recuperar_Contraseña() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icon-user.png"));
        setIconImage(icon);
        setVisible(true);
        cerrar();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txt_confirmacion = new javax.swing.JPasswordField();
        btn_recuperar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperar Contraseña");
        setMinimumSize(new java.awt.Dimension(650, 385));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 105, 103,80));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RECUPERACIÓN DE CONTRASEÑA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 13, 404, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 64, 84, 17);

        txt_user.setBackground(new java.awt.Color(102, 105, 103,80));
        txt_user.setForeground(new java.awt.Color(70, 70, 91));
        txt_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_user);
        txt_user.setBounds(166, 59, 253, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña Nueva:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 114, 132, 17);

        txt_contraseña.setBackground(new java.awt.Color(102, 105, 103,80));
        txt_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_contraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_contraseña);
        txt_contraseña.setBounds(166, 109, 253, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirme Contraseña:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 161, 144, 17);

        txt_confirmacion.setBackground(new java.awt.Color(102, 105, 103,80));
        txt_confirmacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_confirmacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_confirmacion);
        txt_confirmacion.setBounds(166, 156, 253, 29);

        btn_recuperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/password.png"))); // NOI18N
        btn_recuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recuperarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_recuperar);
        btn_recuperar.setBounds(200, 240, 59, 61);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("RECUPERAR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 220, 87, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 20, 430, 300);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\argue\\Documents\\GitHub\\prestamo\\src\\Imagenes\\fondoo.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-230, -40, 1070, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_recuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recuperarActionPerformed
        String user     = txt_user.getText();
        String pass     = new String(txt_contraseña.getPassword());
        String confirm  = new String(txt_confirmacion.getPassword());
        String qry = "";
        ResultSet result;
        
        //VALIDACIONES  
        if(user.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el campo Usuario", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            qry = "SELECT count(*) FROM tbl_usuarios WHERE usuario = ?";
            try{
                //Buscando usuario en BD Para reestablecer contraseña
                PreparedStatement stm = cnx.getConnection().prepareStatement(qry);
                stm.setString(1, user);
                result = stm.executeQuery();
                result.next();
                if(result.getString(1).equals("1")){
                    //Si el usuario existe en BD hacer update con la contraseña nueva
                    if(pass.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Ingrese el campo Contraseña Nueva", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }else{
                        if(confirm.isEmpty()){
                            JOptionPane.showMessageDialog(null, "Confirme la contraseña nueva", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }else{
                            if(!pass.equals(confirm)){
                                JOptionPane.showMessageDialog(null, "Contraseñas no coinciden", "ERROR", JOptionPane.WARNING_MESSAGE);
                            }else{
                                qry = "UPDATE tbl_usuarios SET contraseña = ? WHERE usuario = ?";
                                PreparedStatement stm2 = cnx.getConnection().prepareStatement(qry);
                                stm2.setString(1, pass);
                                stm2.setString(2, user);
                                int upd_error = stm2.executeUpdate();
                                if(upd_error > 0){
                                    JOptionPane.showMessageDialog(null, "Contraseña Reestablecida Exitosamente!", "Recuperacion", JOptionPane.INFORMATION_MESSAGE);
                                    //Abriendo form login
                                    MainLogin mainLogin = new MainLogin();
                                    mainLogin.setVisible(true);
                                    mainLogin.setLocationRelativeTo(this);
                                    this.setVisible(false);
                                }else{
                                    JOptionPane.showMessageDialog(null, "Error al reestablecer contraseña, intente nuevamente", "ERROR", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        }
                        
                    }
                    
                    
                }else{
                    //Si el usuario no existe en BD
                    JOptionPane.showMessageDialog(null, "Usuario Incorrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex, "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btn_recuperarActionPerformed
     public void cerrar() {
        try {
            this.setDefaultCloseOperation(form_newcobrador.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            }
            );
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desa Salir?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_Recuperar_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_Recuperar_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_Recuperar_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_Recuperar_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_Recuperar_Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_recuperar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_confirmacion;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
