/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import com.sun.corba.se.spi.activation._ActivatorImplBase;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class form_financiar_restante extends javax.swing.JFrame {
    public static double prm_Restante;
    public static int prm_Plazo, prm_IDPrestamo;
    conexcion cnx = new conexcion();
    DecimalFormatSymbols punto = new DecimalFormatSymbols();
    
    /**
     * Creates new form form_financiar_restante
     */
    public form_financiar_restante(double _Restante, int _Plazo, int _IDPrestamo) {
        punto.setDecimalSeparator('.');
        DecimalFormat dc = new DecimalFormat("0.00", punto);
        prm_Restante = _Restante;
        prm_Plazo = _Plazo;
        prm_IDPrestamo = _IDPrestamo;
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icon.jpg"));
        setIconImage(icon);
        setVisible(true);
        setResizable(false);
        this.setLocationRelativeTo(null);
         cerrar();
        chk_plazo.setText("Financiamiento con "+ _Plazo + " cuotas (plazo inicial)");
        chk_plazo.setSelected(true);
        txt_saldo_actual.setText(""+prm_Restante);
        
        if(prm_Restante <= 0){
            JOptionPane.showMessageDialog(this, "Saldo incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            txt_cuota_final.setText("0");
        }else{
            txt_cuota_final.setText(""+dc.format((prm_Restante / prm_Plazo)));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_saldo_actual = new javax.swing.JTextField();
        chk_plazo = new javax.swing.JCheckBox();
        chk_cuotas = new javax.swing.JCheckBox();
        txt_cuotas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cuota_final = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_procesar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(640, 450));
        setPreferredSize(new java.awt.Dimension(684, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("FINANCIAMIENTO SALDO RESTANTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(189, 36, 317, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Saldo Restante Actual");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(125, 93, 132, 17);

        txt_saldo_actual.setEditable(false);
        txt_saldo_actual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_saldo_actual);
        txt_saldo_actual.setBounds(275, 87, 231, 29);

        buttonGroup1.add(chk_plazo);
        chk_plazo.setText("Financiamiento con x cuotas");
        getContentPane().add(chk_plazo);
        chk_plazo.setBounds(125, 157, 381, 25);

        buttonGroup1.add(chk_cuotas);
        chk_cuotas.setText("No. de cuotas personalizadas");
        chk_cuotas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chk_cuotasStateChanged(evt);
            }
        });
        chk_cuotas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chk_cuotasPropertyChange(evt);
            }
        });
        getContentPane().add(chk_cuotas);
        chk_cuotas.setBounds(125, 187, 381, 25);

        txt_cuotas.setText("1");
        txt_cuotas.setEnabled(false);
        txt_cuotas.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_cuotasInputMethodTextChanged(evt);
            }
        });
        txt_cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuotasActionPerformed(evt);
            }
        });
        txt_cuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cuotasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cuotasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cuotasKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cuotas);
        txt_cuotas.setBounds(313, 221, 193, 22);

        jLabel3.setText("Cuotas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(235, 224, 60, 16);

        txt_cuota_final.setEditable(false);
        txt_cuota_final.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_cuota_final);
        txt_cuota_final.setBounds(276, 314, 231, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CUOTA FINAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(175, 320, 83, 17);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(54, 274, 571, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(54, 134, 571, 10);

        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_procesar);
        btn_procesar.setBounds(364, 377, 143, 31);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar);
        btn_cancelar.setBounds(203, 377, 143, 31);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-39, 0, 710, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_cuotasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chk_cuotasPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chk_cuotasPropertyChange

    private void chk_cuotasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chk_cuotasStateChanged
        // TODO add your handling code here:
        punto.setDecimalSeparator('.');
        DecimalFormat dc = new DecimalFormat("0.00", punto);
        if(chk_cuotas.isSelected() == true){
            txt_cuotas.setEnabled(true);
        }else{
            txt_cuotas.setText("");
            txt_cuota_final.setText(""+dc.format((prm_Restante / prm_Plazo)));
            txt_cuotas.setEnabled(false);
        }
    }//GEN-LAST:event_chk_cuotasStateChanged

    private void txt_cuotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuotasKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_cuotasKeyTyped

    private void txt_cuotasInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_cuotasInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_cuotasInputMethodTextChanged

    private void txt_cuotasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuotasKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_cuotasKeyPressed

    private void txt_cuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cuotasActionPerformed

    private void txt_cuotasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuotasKeyReleased
        // TODO add your handling code here:
        punto.setDecimalSeparator('.');
        DecimalFormat dc = new DecimalFormat("0.00", punto);
        if(!txt_cuotas.getText().equals("")){
            System.out.println(txt_cuotas.getText());
            double cuotas = Integer.parseInt(txt_cuotas.getText());
            if(cuotas <= 0){
                cuotas = 1;
            }
            System.out.println(prm_Restante / cuotas);
            txt_cuota_final.setText(""+dc.format((prm_Restante / cuotas)));
        }
        
    }//GEN-LAST:event_txt_cuotasKeyReleased

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        int cuotas = 0;
        int SQL_STATUS = 0;
        double financiado = 0;
        String query = "";
        PreparedStatement stm;
        boolean valid = false;
        
        if(chk_plazo.isSelected() == true){
            cuotas = prm_Plazo;
        }else{
            if(chk_cuotas.isSelected() == true){
                if(txt_cuotas.getText().equals("")||Integer.parseInt(txt_cuotas.getText())<=0){
                    valid = false;
                }else{
                    valid = true;
                    cuotas = Integer.parseInt(txt_cuotas.getText());
                }
                
            }
        }
        if(valid){
            financiado = Double.parseDouble(txt_cuota_final.getText()); 
            if(financiado > 0){
                try {
                    if(cuotas > prm_Plazo){
                        query = "UPDATE tbl_prestamo SET cuota_faltante = ?, total_cuota = ?,  cuotas = ? WHERE id_prestamo = ?";   
                        stm= cnx.getConnection().prepareStatement(query);
                        stm.setInt(1, cuotas);
                        stm.setDouble(2, financiado);
                        stm.setDouble(3, cuotas);
                        stm.setInt(4, prm_IDPrestamo);

                    }else{
                        query = "UPDATE tbl_prestamo SET cuota_faltante = ?, total_cuota = ? WHERE id_prestamo = ?";
                        stm = cnx.getConnection().prepareStatement(query);
                        stm.setInt(1, cuotas);
                        stm.setDouble(2, financiado);
                        stm.setInt(3, prm_IDPrestamo);
                    }    

                    SQL_STATUS = stm.executeUpdate();
                    if(SQL_STATUS > 0){
                        JOptionPane.showMessageDialog(this, "Extra Financiamiento Aplicado!");
                        form_pago_cliente frm_pago = new form_pago_cliente();
                        frm_pago.invalidate();
                        frm_pago.validate();
                        frm_pago.repaint();
                        this.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(this, "Error al aplicar extra-financiamiento, intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this, "Error al aplicar extra-financiamiento en base de datos, intente de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Error en cuota cuota final, saldo incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese una cuota valida", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desea regresar?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            form_principal frm = new form_principal();
            frm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cerrar() {
        try {
            this.setDefaultCloseOperation(form_newcobrador.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            }
            );
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desea Salir?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);

        }
    }
    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        form_pago_cliente frm_pago = new form_pago_cliente();
        frm_pago.invalidate();
        frm_pago.validate();
        frm_pago.repaint();
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_financiar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_financiar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_financiar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_financiar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_financiar_restante(prm_Restante, prm_Plazo, prm_IDPrestamo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_procesar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk_cuotas;
    private javax.swing.JCheckBox chk_plazo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txt_cuota_final;
    private javax.swing.JTextField txt_cuotas;
    private javax.swing.JTextField txt_saldo_actual;
    // End of variables declaration//GEN-END:variables
}
