/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class frm_modificar_restante extends javax.swing.JFrame {
    public static double prm_Restante;
    public static int prm_idprestamo;
    public static int prm_cuota;
    public conexcion cnx = new conexcion();

    /**
     * Creates new form frm_modificar_restante
     */
    public frm_modificar_restante(double _Restante, int _Cuotas, int _IDPrestamo) {
        prm_Restante    = _Restante;
        prm_idprestamo  = _IDPrestamo;
        prm_cuota       = _Cuotas;
        initComponents();
        setResizable(false);
        cerrar();
        this.setResizable(false);
        
        txt_saldo_actual.setText(""+prm_Restante);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_modify_saldoRestante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn_procesar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_saldo_actual = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Intereses Generados");
        setMinimumSize(new java.awt.Dimension(640, 341));
        getContentPane().setLayout(null);

        txt_modify_saldoRestante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_modify_saldoRestante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modify_saldoRestanteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_modify_saldoRestante);
        txt_modify_saldoRestante.setBounds(273, 184, 231, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Saldo Restante Final");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(134, 190, 121, 17);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(54, 134, 571, 10);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("MODIFICAR SALDO RESTANTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(175, 25, 262, 22);

        btn_procesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        btn_procesar.setText("  Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_procesar);
        btn_procesar.setBounds(339, 253, 143, 42);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Saldo Restante Actual");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(125, 93, 132, 17);

        txt_saldo_actual.setEditable(false);
        txt_saldo_actual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_saldo_actual);
        txt_saldo_actual.setBounds(275, 87, 231, 29);

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btn_cancelar.setText("  Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar);
        btn_cancelar.setBounds(178, 253, 143, 42);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1, -5, 630, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        double SaldoModify = 0;
        PreparedStatement stm;
        
        SaldoModify = Double.parseDouble( txt_modify_saldoRestante.getText());
        if(SaldoModify < 0){
            JOptionPane.showMessageDialog(this, "No puede ingresar cantidades negativas", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                double total_cuota = SaldoModify / prm_cuota;
                
                String query = "UPDATE tbl_prestamo SET saldo_faltante = "+SaldoModify+", total_cuota = "+total_cuota+" WHERE (id_prestamo = "+prm_idprestamo+")";
                stm = cnx.getConnection().prepareStatement(query);
                int SQL_STATUS = stm.executeUpdate();
                if(SQL_STATUS > 0){
                    JOptionPane.showMessageDialog(this, "Modificacion de saldo aplicada!");
                    form_pago_cliente frm_pago = new form_pago_cliente();
                    frm_pago.invalidate();
                    frm_pago.validate();
                    frm_pago.repaint();
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Error al aplicar modificacion, intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, ex +"Error al aplicar modificacion, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
       
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        form_pago_cliente frm_pago = new form_pago_cliente();
        frm_pago.invalidate();
        frm_pago.validate();
        frm_pago.repaint();
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt_modify_saldoRestanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modify_saldoRestanteKeyTyped
       char valida = evt.getKeyChar();
        if (Character.isLetter(valida) || Character.isWhitespace(valida) || evt.getKeyChar() == KeyEvent.VK_COMMA) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txt_modify_saldoRestanteKeyTyped

     public void cerrar() {
        try {
            this.setDefaultCloseOperation(form_newcobrador.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            }
            );
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desea Salir?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_modificar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_modificar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_modificar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_modificar_restante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_modificar_restante(prm_Restante, prm_cuota, prm_idprestamo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txt_modify_saldoRestante;
    private javax.swing.JTextField txt_saldo_actual;
    // End of variables declaration//GEN-END:variables
}
